### ISSUE TITLE
Save Button not there

### ISSUE THREAD

**Issue by nelliemuller** [rabser/moodle-auth_googleoauth2#229] opened 2017-02-18 20:19 UTC
The save button is not there anymore. I'm using Essential Theme.

**Comment by mouneyrac** [comment] 2017-03-31 00:12
Hi Nellie, it is an known issue. If you refresh the login page they should reappear (somehow something with the cache or probably the way JS is loaded. A workaround solution is to hardcode the call to the buttons in the theme layout.)

**Comment by mouneyrac** [comment] 2017-03-31 00:17
just noticed it is a duplicate of 225.

**Comment by rabser** [comment] 2017-04-20 12:04
Did you solved ?

**Comment by nelliemuller** [comment] 2017-04-20 12:08
Hi Sergio,

Yes, thank you. I increased the memory of the Moodle site and the save icon
appeared again.

Thank you.



Warm wishes,

Dr. Nellie Deutsch <http://goo.gl/7BgeKM>
Education Technology & Leadership Consultant
Organizes MOOCs & Free Online Events
Moodle for Teachers Free Training <https://moodle4teachers.org>
Moodle for Kids Projects <http://moodle4kids.org>
Ed Media Executive Committee Member
<https://www.aace.org/conf/edmedia/committeeEC.htm>
+1.6479640183
[image: Linkedin] <http://ca.linkedin.com/in/nelliemuller>[image: Facebook]
<http://www.facebook.com/drnelliedeutsch>[image: Twitter]
<http://twitter.com/nelliemuller>

**Comment by rabser** [comment] 2017-04-20 12:19
thanks for the prompt reply.

**Closed** 2017-04-20 12:18 UTC
Labels: Bug
